version: '3.8'

services:
  build-apps:
    command:
  home:
    image: home
    build:
      context: .
      dockerfile: /apps/home/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200

  browse:
    image: browse
    build:
      context: .
      dockerfile: /apps/browse/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4201:4201

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
