version: '3.8'

services:
  home:
    image: home
    build:
      dockerfile: ./apps/home/Dockerfile
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001

  browse:
    image: browse
    build: ./apps/browse/Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3002:3002

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
