version: '3.8'

services:
  home:
    image: home
    build:
      context: .
      dockerfile: Dockerfile-home
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  browse:
    image: browse
    build:
      context: .
      dockerfile: Dockerfile-browse
    environment:
      NODE_ENV: production
    ports:
      - 4201:4201

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
